### ISSUE TITLE
Request Bypass Scope 

### ISSUE THREAD

**Issue by falfan2018** [hellshltd/Universal-Bypass#16]
Filehosting : http://www.share-online.biz/dl/L5R4CH9P9YL/free/
https://megaup.net/4Ikt/MSO-09-720p-SAMEHADAKU.TV.mkv
http://www.owndrives.com/d103yuxi087v
https://filebebo.com/d/fi3e6avupipm

http://www.animanganews.com/p/5-things-to-look-for-before-starting.html?url=IyNNJTFEJTE5JTFGJTFBJTA3RSUwN0VHSyUwNk1LSVpHWlpBRSUwNyUwNyUxMiU1QlglNUMlNUMlNDAjIw%3D%3D

Thanks

**Comment by timmyrs** [comment]
- Share-Online.biz Bypass has been added in 3.3 which I will release soon
- I didn't bother to bypass owndrives.com because you have to wait 3 seconds during which you can fill the captcha, which will usually take more than 3 seconds.
- FileBebo.com Bypass has been added
- Safelink Template (used by Animanganews.com) Bypass has been added in 3.3 which I will release soon
