### ISSUE TITLE
Request bypass scope

### ISSUE THREAD

**Issue by alvahn** [hellshltd/Universal-Bypass#7]
example link : http://lindung.in/most-common-heart-diseases/?d=aHR0cHM6Ly85NGxhdWluLmNvbS9Md2V5aw==#landing

https://aklabs.tech/2018/01/08/take-a-closer-look-at-cover-note-and-its-functions/?url=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL29wZW4/aWQ9MTI2aU1PVFNrSXZiSmNHbEJjbG1KcWI1dHFidXFGbHFK

https://ouo.io/norvsX

https://filecrypt.cc/Container/D6A04B37CD.html

https://redwap77.blogspot.com/2018/03/acupuncture-with-simulator.html?url=aHR0cDovL2tiYWdpLmNvbS9Mb2xpYmF0Y2gvYW5pbWUtYmF0Y2gzLTU4Mzg5MS95dXJ1eXVyaXNhbmhhaWJkNzIwcCw1NjI2MTIzLGdhbGxlcnksMSw1LnJhcg

http://davinsurance.com/guide-to-contract-travel-insurance/?aHR0cHM6Ly91c2Vyc2Nsb3VkLmNvbS84dHQxYWFjYmR2NWg=#downloadHehe

http://skyinsurance.ml/5-tips-for-getting-the-right-contents-insurance/?aHR0cDovL3d3dzIxLnppcHB5c2hhcmUuY29tL3YvdW5YcUptaGkvZmlsZS5odG1s

https://www.biargreget.top/p/convert.html?id=aHR0cHM6Ly93d3cubWlycm9yY3JlYXRvci5jb20vZmlsZXMvMFpYSDdSR0wvU25TUzNfMjBfWzcyMHBdW0FuaW1lcnNpbmRvLmNvbV0ubWt2X2xpbmtz

https://forexbrokers.download/recommended-forex-brokers-3-reasons-to-make-the-switch-to-loyal-forex-today/?d=aHR0cDovL2ZvcmV4YnJva2Vycy5kb3dubG9hZC8/cj1hSFIwY0RvdkwzTTJMbXRpWVdkcExtTnZiUzlHWVdScExXdDFiaTloYm1sdFpTMHpMVFl4TURRMU5DOXJkWE52Ym1sdFpTMXpaV3R2YkdGb0xXcDFaR2t0YkdFdE1qQXhPQzAzTWpCd0xEVTROVGMzT0Rnc2JHbHpkQ3cwTERFdWNtRnk=#landing

http://xydeyou.com/?site=aHR0cDovL2tiYWdpLmNvbS9TdHJlQU9OL2FuaWJhdGNoLWluLTExODk1My9hbmliYXRjaC1vdmVybG9yZCwxMjEzNTcyLGxpc3QsNCwxLnJhcg==&c=c=

http://kuhaku.cf/2017/07/31/insurance-allstate-company/?aHR0cHM6Ly91c2Vyc2Nsb3VkLmNvbS9rbTI3dXM0dnczbWI=

http://www.erp-software-services.review/2018/03/tips-to-get-more-value-out-of-your.html?url=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL29wZW4/aWQ9MEI5VHZiRXp2TnZLNmJ6TjROVGcwT1hZelRFRQ==

http://www.wibuu.info/peluncuran-galaxy-s9/?url=aHR0cDovL3MyMS5rdW1wdWxiYWdpLmNvbS9kdW5hbmFydXRvaW5kbzEvYm94eC1vZmZpY2UtbWVpLTMtMjAxOC02NTczNDEvZmlsbWluZG8tbmV0LWEtd3JpbmtsZS1pbi10aW1lLTcyMHBiZCw2MTk4Njk2LGxpc3QsMSwxLm1rdg==

https://zonawibu.bid/how-to-use-a-paper-wallet/?go=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xWmhoWjB5MnJJQ3dXazV4MVRKRVVDQjlsTGlXaGRSWHYvdmlldw==

http://fmlawkers.club/find-right-car-insurance/?site=aHR0cHM6Ly9zaG9ydC5hbmlmaWxlcy5vcmcvN2NWWDY=&c=0&user=2

SafeLinkConverter[dot]Com : 1.http://awsubsco.cf/en/cost/bit.ly?id=aHR0cDovL2JfdC5seS8yR09IOE5N&c=1&user=61942
2.http://safelinkreviewx.com/en/cost/uptobox.com?id=aHR0cHM6Ly8qcHQoYih4LmMobS9kZ2dfOWJqbnA1ODY=&c=1&user=16154
3.https://www.safelinkmbahhanif.top/p/safelink-mbah-hanif.html?url=aHR0cDovL3VwbG9hZC5tb2JpLzI2MzMwMy9EWUFjcHZW

idsly/safelinku(.bid.com) : 1.https://idsly.bid/full/?api=17c57fc455d823bc4a92e62be1af508e08a39ae9&url=https%3A%2F%2Fdrive.google.com%2Ffile%2Fd%2F1J8vVCe3tKNjBbyxhP_iiTFgHd2YFlLIh%2Fview&type=2
2. idsly.com/oc43
3. safelinku.net/3ItTuBjI

thank you very much

**Comment by timmyrs** [comment]
1. lindung.in is already bypassed because it uses the Soralink Plugin
2. aklabs.tech bypass has been added in 3.0 which I will release soon
3. ouo.io has no timer and I can't bypass the captcha
4. filecrypt.cc has no timer and I can't bypass the captcha
5. redwap77.blogspot.com bypass has been added in 3.0 which I will release soon
6. davinsurance.com seems to be broken
7. skyinsurance.ml seems to be broken
8. biargreget.top seems to be bypassed in 3.0 which I will release soon
9. forexbrokers.download seems to be bypassed in 3.0 which I will release soon
10. xydeyou.com doesn't seem to have anything to bypass
11. kuhaku.cf doesn't seem to have anything to bypass
12. erp-software-services.review seems to be bypassed in 3.0 which I will release soon
13. wibuu.info seems to be bypassed in 3.0 which I will release soon
14. zonawibu.bid doesn't seem to have anything to bypass
15. fmlawkers.club seems to be broken
16. SafeLinkReview bypass has been added in 3.0 which I will release soon
17. idsly seems to be bypassed in 3.0 which I will release soon

Thanks for your suggestions, but please check your links before submitting them next time, so I don't have to waste my time on that.

**Comment by RaveN0X87** [comment]
sorry i'll check the links before submitting next time
thanks

**Comment by alvahn** [comment]
Sorry i'll check the links before submitting next time
Thanks before
